server:
  port: 3301
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:12345/eureka/,http://server2:12222/eureka/
  instance:
    preferIpAddress: true
spring:
  application:
    name: config-server
  cloud:
     config:
        server:
          git:
            uri: https://github.com/yxy-SpringBootDemo/springcloudConfig #配置文件所在仓库
            username: yuxiangying #登录账号
            password: 151803yxy #登录密码
            default-label: master #配置文件分支
            search-paths: config  #配置文件所在根目录